---
- hosts: 172.31.35.93
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
     name: apache2
     state: present

  - name: copy index.hmtl into file int nodes side
    copy: 
     src: index.html
     dest: /var/www/html/index.html

  - name: copy myindex.j2 file into node side
    template:
     src: myindex.j2
     dest: /var/www/html/index.html

  - name: i want to download files from internet
    get_url:
     url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes

 