---
- hosts: 172.31.35.93
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
     name: apache2
     state: present

  - name: copy index.hmtl into file int nodes side
    copy: 
     ser: index.html
     dest: /var/www/html/index.html

 